# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GuanaHacks 2018"
email: "kaizen.ugto@gmail.com"
description: "GuanaHacks - Hackat贸n estudiantil de la Universidad de Guanajuato."
baseurl: ""
url: "https://futurelabmx.github.io"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Future Lab"
organizerAlternateName: "Future Lab"
organizerDescription: "Laboratorio Estudiantil de Innovaci贸n Cient铆fica y Tecnol贸gica de la Universidad de Guanajuato."
organizerEmail: "r.mirontorres@ugto.mx"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "www.facebook.com/f.lab.mx"

# Head
metaKeywords: "event, mlh, devfest, hackathon, programming, guanajuato, hack, guanahacks, ugto, future lab, kaizen ug"
twitterAccount: "@FerroRodolfo"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
# c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Inicio"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/programa/", text: "Programa"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Equipo"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
  - {permalink: "/resumen", text: "Resumen"}

rightNavigationButtons:
  - {permalink: "/resumen", text: "Resumen"}


# Hero Block
heroImage: "hero.jpg"
heroTitle: "GuanaHacks. Hecho para <typeout>"
eventDate: "18-20 Mayo, 2018"
typeoutTextValues: '"", "creadores.", "hackers.", "l铆deres.", "ti."'
typeoutFallback: ""
heroButtons:
 - {permalink: "/resumen", text: "Resumen"}


# About Block
aboutTitle: "Acerca de GuanaHacks"
aboutBlock:
 - {title: "Conferencias", image: "conference.jpg", text: "L铆deres de la industria local compartir谩n su experiencia. Las nuevas tecnolog铆as y su utilizaci贸n para soluciones ingeniosas." }
 - {title: "Talleres", image: "workshop.jpg", text: "Aprende a desarrollar tu idea, desde el prototipo a un modelo de negocios. Impartidos por expertos en el tema, de dise帽o, negocios y t茅cnicos." }


# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "+", info: "Estudiantes", detail: "隆Del estado y de la rep煤blica!"}
 - {count: "55", specialCharacter: "+", info: "Horas", detail: "隆De actividades y desarollo!"}
 - {count: "6", specialCharacter: "+", info: "Talleres y conferencias", detail: "隆De diversos temas y 谩reas!"}
 - {count: "10", specialCharacter: "+", info: "Mentores", detail: "隆Experto en 谩rea!"}


# Latest News Block
latestNewsTitle: "Ultimas noticias"


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Invitados Especiales"
rockstarSpeakersButtonText: "Ver todos los ponentes"


# Location Block
locationBlockTitle: "Ubicaci贸n"
eventLocationName: "Aulas Magnas, Campus Guanajuato, Universidad de Guanajuato."
eventLocationLink: "http://www.ugto.mx/campusgto/"
eventStreetAddress: "El Establo, Marfil."
eventAddressLocality: "Guanajuato."
eventAddressLocalityRegion: "Gto."
eventPostalCode: "36000"
eventAddressCountry: "M茅xico"
eventStartTime: "2018-05-18T12:00"
eventDoorTime: "10:00"
eventEndTime: "2018-05-20T14:00"
eventPlaceCoordinates: "21.012597, -101.275503"
mapCenterCoordinates: "21.012597, -101.275503"
mapMobileCenterCoordinates: "21.012597, -101.275503"


# Venue Block
# venueBlockTitle: "Lugar"
# venueBigImage: "venue_0.jpg"
# venueSmallImage1: "venue_1.jpg"
# venueSmallImage2: "venue_2.jpg"
# venueSmallImage3: "venue_3.jpg"
# venueTitle: "Kinopalace Cinema"
# venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]


# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Wanna hack?"
twitterHashTag: "GuanaHacks"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"


# Partners Block
organizersTitle: "Powered by"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Convi茅rtete en sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://twitter.com/search?q=%23GuanaHacks", icon: "twitter"}
 - {link: "https://facebook.com/f.lab.mx", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.ugto.mx/", text: "Universidad de Guanajuato"}
   - {link: "https://www.facebook.com/GuanaHacks/", text: "GuanaHacks"}
   - {link: "http://www.facebook.com/f.lab.mx/", text: "Future Lab"}
   - {link: "https://www.facebook.com/KaizenUG/", text: "Kaizen UG"}
 -
  title: "Contacto"
  links:
   - {link: "mailto:guanahacks@gmail.com", text: "GuanaHacks"}
   - {link: "mailto:r.mirontorres@ugto.mx", text: "Future Lab"}
   - {link: "mailto:kaizen.ugto@gmail.com", text: "Kaizen UG"}
 -
  title: "FAQ"
  links:
   - {link: "https://guanahacks.com/programa/", text: "Programa del evento"}
   - {link: "https://guanahacks.com/conducta/", text: "C贸digo de Conducta"}
   - {link: "https://guanahacks.com/recomendaciones/", text: "Consideraciones y recomendaciones"}

# Blog
blogTitle: "ltimas noticias"
blogCommentsEnabled: true
# discusShortName: "devfestua"  # HERE

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Acerca de nosotros"
aboutUs: "Entusiastas por el desarrollo de los j贸venes, el emprendimiento y la innovaci贸n, el quipo organizador de GuanaHacks 2018
se conforma por estudiantes de la Universidad de Guanajuato. Representado a 2 grupos organizados de la misma: Future Lab y Kaizen UG."

# Hackathon
hackathonTitle: "GuanaHacks"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Conoce las tem谩ticas"
hackathonRows:
 - {title: "Seguridad ", image: "safety.png", details: "
 Seguridad P煤blica  \n
 Seguridad Ante desastres  \n
 Seguridad Estudiantil  \n
 Seguridad Tur铆stica  \n
 Seguridad del Hogar "}

# Hackathon Judges Block
judgesImage: "statistic.png"
judgesTitle: "Jueces"

# Hackathon Prizes Block
prizesTitle: "Premios"
prizes:
 - {title: "2do Lugar", image: "prize.png", info: "$$ para tu proyecto, GitHub Pack, Entradas a Campus Party 2018 y TalentLand 2019"}
 - {title: "1er Lugar", image: "prize.png", info: "$$$ para tu proyecto, Incubaci贸n, GitHub Pack, Entradas a Campus Party 2018 y TalentLand 2019"}
 - {title: "3er Lugar", image: "prize.png", info: "$ para tu proyecto, GitHub Pack"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Ubicaci贸n"
hackathonLocationName: "GuanaHacks"
hackathonLocationLink: "http://guanahacks.com"
hackathonStreetAddress: "Divisi贸n de Ciencias Econ贸mico Administrativas"
hackathonAddressLocality: "Guanajuato"
hackathonAddressLocalityRegion: "Guanajuato"
hackathonPostalCode: "36000"
hackathonAddressCountry: "Mexico"
hackathonTimeTitle: "Registro"
hackathonStartTime: "2018-05-18T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2018-05-20T13:30"
viewOnMap: "Ver en Google Maps"
hackathonPlaceCoordinates: "21.012597, -101.275503"
hackathonMapCenterCoordinates: "21.012597, -101.275503"
hackathonMapMobileCenterCoordinates: "21.012597, -101.275503"
